version: '2'

services:
    postgres:
        image: postgres-imagen
        build: ./postgres/.
        container_name: 'psqlalpine-prn335'
        environment:
           - POSTGRES_USER=mortal2017
           - POSTGRES_PASSWORD=prn335
           - POSTGRES_DB=posts
        ports:
           - '5432:5432'
        volumes:
           - pgdata:/var/lib/postgresql/data
    payaraserver:
            image: 'payara-imagen'
            build: ./payara/.
            container_name: 'payara-prn335'
            ports: 
             - '8080:8080'
             - '4848:4848'
            entrypoint:
             - "bin/asadmin"
             - "start-domain"
             - "-v"     
volumes:
     pgdata:

SELECT DISTINCT c.comentario FROM Cometario c JOIN PostPaso pp WHERE c.aprobado = false and c.fecha BETWEEN '2017-09-09' AND '2017-09-14'AND pp.postPasoPK.idPost IN (SELECT pp1.postPasoPK.idPost FROM PostPaso pp1 WHERE pp1.paso.nombre = 'PUBLICADO')
